
obj-$(CONFIG_CHROMEOS)		+= chromeos.o
obj-$(CONFIG_CHROMEOS_OF_FIRMWARE) += chromeos_arm.o
obj-$(CONFIG_CHROMEOS_LAPTOP)	+= chromeos_laptop.o
obj-$(CONFIG_CHROMEOS_PSTORE)	+= chromeos_pstore.o
obj-$(CONFIG_CHROMEOS_VBC_EC)	+= chromeos_vbc_ec.o
