obj-$(CONFIG_TEGRA_PCM) += tegra_pcm_rpc.o
obj-$(CONFIG_TEGRA_I2S) += tegra_i2s.o tegra_transport.o
obj-$(CONFIG_TEGRA_SND_WHISTLER) += tegra_whistler.o
obj-$(CONFIG_TEGRA_SND_HARMONY) += tegra_harmony.o
