dtb-$(CONFIG_ARCH_TEGRA) += tegra132-norrin.dtb
dtb-$(CONFIG_ARCH_TEGRA) += tegra210-foster.dtb
dtb-$(CONFIG_ARCH_TEGRA) += tegra210-smaug-p0.dtb
dtb-$(CONFIG_ARCH_TEGRA) += tegra210-smaug-p1.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
