obj-$(CONFIG_AUFS) += aufs.o

aufs-objs := module.o super.o sbinfo.o branch.o xino.o sysaufs.o opts.o \
	wkq.o vfsub.o dcsub.o cpup.o whout.o plink.o wbr_policy.o \
	dentry.o dinfo.o file.o f_op.o finfo.o dir.o vdir.o inode.o i_op.o \
	i_op_add.o i_op_del.o i_op_ren.o iinfo.o misc.o sysfs.o debug.o
