#
# Makefile for Chromeos Supplied Third-Party device drivers
#

obj-$(CONFIG_ATH6K_LEGACY)	+= ath6kl/
obj-$(CONFIG_R8103)	+= rtl8103/r8101-1.014.00/src/

# This is a stupid trick to get kbuild to create chromeos/built-in.o
obj- += foo.o
