#
# Makefile for the Linux kernel ubuntu supplied third-party device drivers.
#

obj-$(CONFIG_BLK_DEV_DRBD)	+= drbd/

obj-$(CONFIG_SCSI_ISCSITARGET)	+= iscsitarget/

obj-$(CONFIG_SQUASHFS)		+= squashfs/

obj-$(CONFIG_AUFS)		+= aufs/

obj-$(CONFIG_ATL2)		+= atl2/

obj-$(CONFIG_NET_ET131X)	+= et131x/
