obj-$(CONFIG_NET_ET131X)	+= et131x.o

et131x-objs += et131x_main.o et131x_initpci.o et131x_isr.o et131x_netdev.o \
	et131x_supp.o et131x_config.o et131x_debug.o ET1310_jagcore.o \
	ET1310_tx.o ET1310_rx.o ET1310_phy.o ET1310_mac.o ET1310_pm.o \
	ET1310_eeprom.o
