dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-evb.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-oak-rev0.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-oak-rev1.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-oak-rev2.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-oak-rev3.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
