obj-$(CONFIG_ARCH_TEGRA) += fuse/

obj-$(CONFIG_ARCH_TEGRA) += common.o
obj-$(CONFIG_ARCH_TEGRA) += flowctrl.o
obj-$(CONFIG_ARCH_TEGRA) += pm.o
obj-$(CONFIG_ARCH_TEGRA) += pmc.o

obj-$(CONFIG_TEGRA_PROC_POWER_MODEL) += tegra_ppm.o
