obj-$(CONFIG_ARCH_TEGRA) += fuse/
obj-$(CONFIG_TEGRA_SYS_EDP) += sysedp/

obj-$(CONFIG_ARCH_TEGRA) += common.o
obj-$(CONFIG_ARCH_TEGRA) += flowctrl.o
obj-$(CONFIG_ARCH_TEGRA) += pm.o
obj-$(CONFIG_ARCH_TEGRA) += kfuse.o
obj-$(CONFIG_ARCH_TEGRA) += pmc.o

obj-$(CONFIG_TEGRA_BPMP_MAILMAN) += tegra-bpmp-mailman.o
obj-$(CONFIG_TEGRA_PROC_POWER_MODEL) += tegra_ppm.o
obj-$(CONFIG_TEGRA_CPU_EDP)	+= tegra_cpu_edp.o

obj-$(CONFIG_TEGRA_DVFS)       += tegra-dvfs.o
obj-$(CONFIG_TEGRA_124_DVFS)   += tegra124-dvfs.o
obj-$(CONFIG_TEGRA_210_DVFS)   += tegra210-dvfs.o
