#!/usr/bin/perl

if ($#ARGV != 1) {
	die "Usage: $0 <stop at> <start at>\n";
}
my ($end, $start) = @ARGV;

$end =~ s/.*\.//;
$start =~ s/.*\.//;

my @changes = ();
my $output = 0;
open(CHG, "<debian/changelog.ubuntu") ||
	open(CHG, "<debian/changelog") ||
	die "$0: debian/changelog: open failed - $!\n";
while (<CHG>) {
	if (/^\S+\s+\((.*\.(\d+))\)/) {
		if ($2 <= $end) {
			last;
		}
		if ($2 == $start) {
			$output = 1;
		}
		if ($output) {
			push(@changes, "\n  [ Ubuntu: $1 ]\n\n");
			next;
		}
	}
	next if ($output == 0);

	next if (/^\s*$/);
	next if (/^\s--/);
	next if (/^\s\s[^\*\s]/);

	push(@changes, $_);
}
close(CHG);

open(CHANGELOG, "< debian/changelog") or die "Cannot open changelog";
open(NEW, "> debian/changelog.new") or die "Cannot open new changelog";

$printed = 3;
while (<CHANGELOG>) {
	if (/^  CHANGELOG: /) {
		$printed--;
		print NEW;
		if ($printed == 0) {
			print NEW @changes;
		}
		next;
	}
	print NEW;
}

close(NEW);
close(CHANGELOG);

rename("debian/changelog.new", "debian/changelog");
